language: php

sudo: false

php:
    - 5.6
    - 7.0
    - hhvm

before_install:
    - composer self-update
    - phpenv config-rm xdebug.ini || true

before_script:
    - composer --prefer-source install

script: ./vendor/bin/phpunit
