language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.0
    - 7.1

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_VERSION="~2.8.0"

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION}; fi
    - composer update --optimize-autoloader --no-interaction $COMPOSER_FLAGS

script: make tests
