language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 8.0
    - 8.1

matrix:
    include:
        - { php: 8.0, env: COMPOSER_FLAGS='--prefer-lowest' }

    fast_finish: true

before_install:
    - phpenv config-rm xdebug.ini || true

before_script:
    - composer install $COMPOSER_OPTS

script:
    - php vendor/bin/phpunit
