language: php

sudo: false

php:
  - 5.6

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar --dev --prefer-source install

script: ./vendor/bin/phpunit --coverage-text
