language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.0
    - 7.1

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer update --optimize-autoloader --no-interaction $COMPOSER_FLAGS

script: make tests
