language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install --optimize-autoloader --no-interaction

script: make tests
